/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerOrderRouteImport } from './routes/customer-order'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DesignerIndexRouteImport } from './routes/designer/index'
import { Route as DesignerNotificationsRouteImport } from './routes/designer/notifications'
import { Route as DesignerSettingsRouteImport } from './routes/designer/settings'
import { Route as InvoicesOrderIdRouteImport } from './routes/invoices/$orderId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'
import { Route as OwnerActivityRouteImport } from './routes/owner/activity'
import { Route as OwnerDashboardRouteImport } from './routes/owner/dashboard'
import { Route as OwnerDesignersRouteImport } from './routes/owner/designers'
import { Route as OwnerReportsRouteImport } from './routes/owner/reports'
import { Route as OwnerSettingsRouteImport } from './routes/owner/settings'
import { Route as OwnerInvoicesIndexRouteImport } from './routes/owner/invoices/index'
import { Route as OwnerOrdersIndexRouteImport } from './routes/owner/orders/index'
import { Route as OwnerOrdersNewRouteImport } from './routes/owner/orders/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrderRoute = CustomerOrderRouteImport.update({
  id: '/customer-order',
  path: '/customer-order',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerIndexRoute = DesignerIndexRouteImport.update({
  id: '/designer/',
  path: '/designer/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerNotificationsRoute = DesignerNotificationsRouteImport.update({
  id: '/designer/notifications',
  path: '/designer/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerSettingsRoute = DesignerSettingsRouteImport.update({
  id: '/designer/settings',
  path: '/designer/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesOrderIdRoute = InvoicesOrderIdRouteImport.update({
  id: '/invoices/$orderId',
  path: '/invoices/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerActivityRoute = OwnerActivityRouteImport.update({
  id: '/owner/activity',
  path: '/owner/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/owner/dashboard',
  path: '/owner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerDesignersRoute = OwnerDesignersRouteImport.update({
  id: '/owner/designers',
  path: '/owner/designers',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerReportsRoute = OwnerReportsRouteImport.update({
  id: '/owner/reports',
  path: '/owner/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/owner/settings',
  path: '/owner/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerInvoicesIndexRoute = OwnerInvoicesIndexRouteImport.update({
  id: '/owner/invoices/',
  path: '/owner/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerOrdersIndexRoute = OwnerOrdersIndexRouteImport.update({
  id: '/owner/orders/',
  path: '/owner/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerOrdersNewRoute = OwnerOrdersNewRouteImport.update({
  id: '/owner/orders/new',
  path: '/owner/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customer-order': typeof CustomerOrderRoute
  '/login': typeof LoginRoute
  '/designer/notifications': typeof DesignerNotificationsRoute
  '/designer/settings': typeof DesignerSettingsRoute
  '/invoices/$orderId': typeof InvoicesOrderIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/owner/activity': typeof OwnerActivityRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/designers': typeof OwnerDesignersRoute
  '/owner/reports': typeof OwnerReportsRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/designer/': typeof DesignerIndexRoute
  '/owner/orders/new': typeof OwnerOrdersNewRoute
  '/owner/invoices/': typeof OwnerInvoicesIndexRoute
  '/owner/orders/': typeof OwnerOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customer-order': typeof CustomerOrderRoute
  '/login': typeof LoginRoute
  '/designer/notifications': typeof DesignerNotificationsRoute
  '/designer/settings': typeof DesignerSettingsRoute
  '/invoices/$orderId': typeof InvoicesOrderIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/owner/activity': typeof OwnerActivityRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/designers': typeof OwnerDesignersRoute
  '/owner/reports': typeof OwnerReportsRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/designer': typeof DesignerIndexRoute
  '/owner/orders/new': typeof OwnerOrdersNewRoute
  '/owner/invoices': typeof OwnerInvoicesIndexRoute
  '/owner/orders': typeof OwnerOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customer-order': typeof CustomerOrderRoute
  '/login': typeof LoginRoute
  '/designer/notifications': typeof DesignerNotificationsRoute
  '/designer/settings': typeof DesignerSettingsRoute
  '/invoices/$orderId': typeof InvoicesOrderIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/owner/activity': typeof OwnerActivityRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/designers': typeof OwnerDesignersRoute
  '/owner/reports': typeof OwnerReportsRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/designer/': typeof DesignerIndexRoute
  '/owner/orders/new': typeof OwnerOrdersNewRoute
  '/owner/invoices/': typeof OwnerInvoicesIndexRoute
  '/owner/orders/': typeof OwnerOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customer-order'
    | '/login'
    | '/designer/notifications'
    | '/designer/settings'
    | '/invoices/$orderId'
    | '/orders/$orderId'
    | '/owner/activity'
    | '/owner/dashboard'
    | '/owner/designers'
    | '/owner/reports'
    | '/owner/settings'
    | '/designer/'
    | '/owner/orders/new'
    | '/owner/invoices/'
    | '/owner/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customer-order'
    | '/login'
    | '/designer/notifications'
    | '/designer/settings'
    | '/invoices/$orderId'
    | '/orders/$orderId'
    | '/owner/activity'
    | '/owner/dashboard'
    | '/owner/designers'
    | '/owner/reports'
    | '/owner/settings'
    | '/designer'
    | '/owner/orders/new'
    | '/owner/invoices'
    | '/owner/orders'
  id:
    | '__root__'
    | '/'
    | '/customer-order'
    | '/login'
    | '/designer/notifications'
    | '/designer/settings'
    | '/invoices/$orderId'
    | '/orders/$orderId'
    | '/owner/activity'
    | '/owner/dashboard'
    | '/owner/designers'
    | '/owner/reports'
    | '/owner/settings'
    | '/designer/'
    | '/owner/orders/new'
    | '/owner/invoices/'
    | '/owner/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerOrderRoute: typeof CustomerOrderRoute
  LoginRoute: typeof LoginRoute
  DesignerNotificationsRoute: typeof DesignerNotificationsRoute
  DesignerSettingsRoute: typeof DesignerSettingsRoute
  InvoicesOrderIdRoute: typeof InvoicesOrderIdRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OwnerActivityRoute: typeof OwnerActivityRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  OwnerDesignersRoute: typeof OwnerDesignersRoute
  OwnerReportsRoute: typeof OwnerReportsRoute
  OwnerSettingsRoute: typeof OwnerSettingsRoute
  DesignerIndexRoute: typeof DesignerIndexRoute
  OwnerOrdersNewRoute: typeof OwnerOrdersNewRoute
  OwnerInvoicesIndexRoute: typeof OwnerInvoicesIndexRoute
  OwnerOrdersIndexRoute: typeof OwnerOrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-order': {
      id: '/customer-order'
      path: '/customer-order'
      fullPath: '/customer-order'
      preLoaderRoute: typeof CustomerOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer/': {
      id: '/designer/'
      path: '/designer'
      fullPath: '/designer/'
      preLoaderRoute: typeof DesignerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer/notifications': {
      id: '/designer/notifications'
      path: '/designer/notifications'
      fullPath: '/designer/notifications'
      preLoaderRoute: typeof DesignerNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer/settings': {
      id: '/designer/settings'
      path: '/designer/settings'
      fullPath: '/designer/settings'
      preLoaderRoute: typeof DesignerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$orderId': {
      id: '/invoices/$orderId'
      path: '/invoices/$orderId'
      fullPath: '/invoices/$orderId'
      preLoaderRoute: typeof InvoicesOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/activity': {
      id: '/owner/activity'
      path: '/owner/activity'
      fullPath: '/owner/activity'
      preLoaderRoute: typeof OwnerActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/dashboard': {
      id: '/owner/dashboard'
      path: '/owner/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/designers': {
      id: '/owner/designers'
      path: '/owner/designers'
      fullPath: '/owner/designers'
      preLoaderRoute: typeof OwnerDesignersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/reports': {
      id: '/owner/reports'
      path: '/owner/reports'
      fullPath: '/owner/reports'
      preLoaderRoute: typeof OwnerReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/settings': {
      id: '/owner/settings'
      path: '/owner/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OwnerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/invoices/': {
      id: '/owner/invoices/'
      path: '/owner/invoices'
      fullPath: '/owner/invoices/'
      preLoaderRoute: typeof OwnerInvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/orders/': {
      id: '/owner/orders/'
      path: '/owner/orders'
      fullPath: '/owner/orders/'
      preLoaderRoute: typeof OwnerOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/orders/new': {
      id: '/owner/orders/new'
      path: '/owner/orders/new'
      fullPath: '/owner/orders/new'
      preLoaderRoute: typeof OwnerOrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerOrderRoute: CustomerOrderRoute,
  LoginRoute: LoginRoute,
  DesignerNotificationsRoute: DesignerNotificationsRoute,
  DesignerSettingsRoute: DesignerSettingsRoute,
  InvoicesOrderIdRoute: InvoicesOrderIdRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OwnerActivityRoute: OwnerActivityRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  OwnerDesignersRoute: OwnerDesignersRoute,
  OwnerReportsRoute: OwnerReportsRoute,
  OwnerSettingsRoute: OwnerSettingsRoute,
  DesignerIndexRoute: DesignerIndexRoute,
  OwnerOrdersNewRoute: OwnerOrdersNewRoute,
  OwnerInvoicesIndexRoute: OwnerInvoicesIndexRoute,
  OwnerOrdersIndexRoute: OwnerOrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
